apiVersion: console.openshift.io/v1
kind: ConsoleYAMLSample
metadata:
  name: 1-jenkins-platform
spec:
  description: >
    Default PloigosPlatform deployment, with Jenkins for Continuous Integration,
    Nexus for a Container Registry, and SSO disabled
  targetResource:
    apiVersion: redhatgov.io/v1alpha1
    kind: PloigosPlatform
  title: Default PloigosPlatform
  yaml: |
    apiVersion: redhatgov.io/v1alpha1
    kind: PloigosPlatform
    metadata:
      name: ploigosplatform-sample
    spec:
      ploigosPlatform:
        services:
          continuousIntegration:
            jenkins:
              enabled: true
          sourceControl:
            gitea:
              enabled: true
          artifactRepository:
            nexusArtifacts:
              enabled: true
          staticCodeAnalysis:
            sonarqube:
              enabled: true
          continuousDeployment:
            argocd:
              enabled: true
          uat:
            selenium:
              enabled: true
          containerRegistry:
            nexusContainers:
              enabled: true
