---

subdomain: '{{ full_cluster_name }}'

redhat_gov_catalog_tag: "latest"

jenkins_repository_name: openshift-release-dev

platform_tls_verify: "{{ ploigos_platform.tls.verify | default(true) }}"
platform_trust_bundle_config_map: "{{ ploigos_platform.tls.trust_bundle_config_map | default }}"

all_services: "{{ ploigos_platform.services.values() | list | json_query('[].keys(@)[]') }}"

transformed_services: |-
      {% for service in ploigos_platform.services.values()|list %}
      {% for service_name in service.keys()|list %}
      - name: "{{ service_name }}"
        values: {{ service[service_name]|to_json }}
      {% endfor %}
      {% endfor %}

enabled_services: '{{ transformed_services|from_yaml|json_query("[?values.enabled].name") }}'

external_services: '{{ transformed_services|from_yaml|json_query("[?values.external_properties].name") | intersect(enabled_services) }}'

managed_services: '{{ enabled_services | difference(external_services) }}'

target_namespaces: ['{{ ploigos_namespace }}']

## GitLab Variables
gitlab_chart_version: "5.9.1"
gitlab_url: "https://gitlab.apps{{ full_cluster_name }}"
gitlab_ci_trustca_secret: "{{ ploigos_platform.services.continuous_integration.gitlab_ci.ca_secret | default(None) }}"
cert_manager: "{{ ploigos_platform.services.source_control.gitlab.install_cert_manager }}"
