---
- name: Clean up resources
  shell: |
    oc delete -n {{ ploigos_namespace }} KeycloakUser,KeycloakClient,KeycloakRealm --all || true
    oc delete -n {{ ploigos_namespace }} all,configmap,pvc,serviceaccount,rolebinding -l app=jenkins-persistent || true
    oc delete -n {{ ploigos_namespace }} secret gitea-access-token || true
    oc delete -n {{ ploigos_namespace }} secret ploigos-platform-config-secrets || true
    oc delete -n {{ ploigos_namespace }} cm ploigos-platform-config || true

- name: Get values provided by custom resources
  include_tasks: services_configure.yml

- name: Remove CustomResources
  k8s:
    definition: '{{ lookup("template", "custom-resources/" + operator_app + ".yml.j2") }}'
    state: absent
  loop: '{{ managed_services }}'
  loop_control:
    loop_var: operator_app
    label: operator_app
  when: lookup("template", "custom-resources/" + operator_app + ".yml.j2", errors='ignore')

## GitLab specifc task
- name: Tasks for GitLab removal
  block:
    - name: Initialize custom resource GitLab CI details
      when: '"gitlab_ci" in managed_services'
      set_fact:
        service_values: "{{ _gitlab_ci_values | combine(service_values, recursive=true) }}"
      vars:
        _gitlab_ci_values:
          gitlab_ci:
            token_secret: gitlab-group-runner-secret
            gitlab_url: "https://gitlab.apps.{{ full_cluster_name }}"
            build_image: "quay.io/ploigos/ploigos-tool-maven:v0.18.0"

    - name: Remove GitLab Operator
      k8s:
        src: "{{ role_path }}/files/gitlab.yml"
        state: absent

    - name: Delete Gitlab Custom Resources
      k8s:
        definition: '{{ lookup("template", "gitlab-cr/" + operator_app + ".yml.j2") }}'
        state: absent
      loop:
        - cert_manager
        - gitlab_ci
        - gitlab_ci_configmap
        - gitlab_ci_serviceaccount
        - gitlab_ci_binding
        - gitlab_ci_pvc
      loop_control:
        loop_var: operator_app
        label: operator_app
      when: lookup("template", "gitlab-cr/" + operator_app + ".yml.j2", errors='ignore')

    - name: Remove GitLab CI Role
      k8s:
        src: "{{ role_path }}/files/gitlab_ci_role.yml"
        state: absent
  when: '"gitlab" in managed_services'
