---
- name: Initialize custom resource GitLab CI details
  when: '"gitlab_ci" in managed_services'
  set_fact:
    service_values: "{{ _gitlab_ci_values | combine(service_values, recursive=true) }}"
  vars:
    _gitlab_ci_values:
      gitlab_ci:
        token_secret: gitlab-group-runner-secret
        gitlab_url: "https://gitlab.apps.{{ full_cluster_name }}"
        build_image: "quay.io/ploigos/ploigos-tool-maven:v0.18.0"

- name: Apply GitLab CI ClusterRole and Role Binding
  k8s:
    src: "{{ role_path }}/files/gitlab_ci_role.yml"
  register: deployment
  until: not deployment.failed
  retries: 5
  delay: 10

- name: Apply GitLab resources
  k8s:
    definition: '{{ lookup("template", "gitlab-cr/" + operator_app + ".yml.j2") }}'
  register: deployment
  until: not deployment.failed
  retries: 5
  delay: 10
  loop:
    - gitlab_ci
    - gitlab_ci_configmap
    - gitlab_ci_serviceaccount
    - gitlab_ci_binding
    - gitlab_ci_pvc
  loop_control:
    loop_var: operator_app
    label: operator_app
  when: lookup("template", "gitlab-cr/" + operator_app + ".yml.j2", errors='ignore')
